### PR TITLE
Bump version to allow 2.8.0

### PR DESCRIPTION
**Pull request by drewclauson**
I've tested this with 2.8.0 and it works.  3.0 shouldn't be a problem either, but I haven't tested with it yet.

### CODE REVIEW

**Comment by drewclauson** [comment]
Didn't mean to do 3 commits, sorry about that.  I can redo if you prefer.

**Comment by neomerx** [comment]
Yep, would be nice to have 1 commit :wink:

**Comment by drewclauson** [comment]
Crazy, that's the first time a squash has actually worked for me... There you go! :smiley:

**Comment by drewclauson** [comment]
And it works with 3.0 as well, btw

**Comment by neomerx** [comment]
Thanks a lot

**Comment by drewclauson** [comment]
Any plans to tag a release with this? :-)

**Comment by neomerx** [comment]
Done. Sorry :smile:

**Pull request merged**
