### PR TITLE
Updated dependencies to allow installation on Laravel 5.1

### PR DESCRIPTION
**Pull request by shabushabu**
As the title says.

### CODE REVIEW

**Comment by neomerx** [comment]
@shabushabu I'm fine with L5.1 support but please leave "neomerx/json-api": "0.2.2"
For now I'd like to have more control what json-api versions goes to L5. It's just a safety measure. Compatibility should be tested before upgrade.

**Comment by shabushabu** [comment]
Actually, since you're using semver, it follows that anything between 0.2.1 and 0.3 (excl.) should be alright. Seeing that the only Laravel/Symfony bits you're using here are the exceptions I can't see how it wouldn't be compatible, but maybe I'm missing something?

**Comment by neomerx** [comment]
I think ~0.2 means all versions up to 0.999 https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md

**Comment by shabushabu** [comment]
Yup, that's right. The tilde sign works on the last specified digit, though, so ~0.2 does mean anything below 1.0 But if you specify ~0.2.2, then that means anything below 0.3. 

Sent by iPhone.

**Comment by shabushabu** [comment]
Awesome, thanks!

Sent by iPhone.

**Pull request merged**
